Sprint 06
Bogdawaa/MovieQuiz-ios pull request #3
Opened 2023-07-03 19:48 UTC by Bogdawaa

Реализована загрузка данных для квиза по сети. Реализован учет статистики.

2023-07-05 09:12 UTC, protos17 requested changes

2023-07-05 09:12 UTC, protos17 commented on MovieQuiz/Models/QuizStepViewModel.swift
> +import Foundation
При импорте UIKit можно не импортировать Foundation, потому что первый содержит в себе второй

2023-07-05 09:12 UTC, protos17 commented on MovieQuiz/Presentation/AlertPresenter.swift
> +import Foundation
Здесь тоже его можно убрать

2023-07-05 09:12 UTC, protos17 commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    private var statisticService: StatisticService?
Здесь не используется, рекомендую удалить

2023-07-05 09:12 UTC, protos17 commented on MovieQuiz/Presentation/AlertPresenter.swift
> +        })
print'ы не принято сохранять в репозитории, лучше заменить на:

viewController?.present(alert, animated: true)

2023-07-05 09:12 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +//        questionFactory?.requestNextQuestion()
Лишний закомментированный код рекомендую удалять

2023-07-05 09:12 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            activityIndicator.isHidden = false
Рекомендую использовать свойство hidesWhenStopped вместо ручного управления свойством isHidden

2023-07-05 09:12 UTC, protos17 commented on MovieQuiz/Services/MovieLoader.swift
> +        guard let url = URL(string: "https://imdb-api.com/en/API/Top250Movies/k_zcuw1ytf") else {
Эта функциональность уже 6 спринта

2023-07-05 09:12 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +    // Список вопросов
Мок-вопросы при добавлении запросов из сети уже можно не хранить

2023-07-05 09:12 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +                print("Failed to load image")
В этом месте, функция не завершает свою работу и идет формировать вопрос без постера. 
В таком случае, бизнес-логика приложения будет нарушена, потому что пользователь не сможет ответить корректно, ведь изображения нет.
Это состояние стоит обработать, например, с помощью алерта. 
Не забудь, что алерт будет обновлять UI и это тоже нужно учесть (вернуть на main), ровно также, как и прерывание функции (сделать return)

2023-07-05 09:12 UTC, protos17 commented on MovieQuiz/Services/MovieLoader.swift
> +                    let mostPopularMovies = try JSONDecoder().decode(MostPopularMovies.self, from: data)
Обращу внимание на свойство `errorMessage`. 

Здесь может прийти текст с ошибкой, в таком случае сервис обычно возвращает пустой список фильмов `items`. 
С пустым списком приложение будет выглядеть сломанным. 
Это состояние называют краевым случаем, его стоит обрабатывать как ошибку, например, показывать алерт.
С точки зрения проектирования API сервиса IMDB, 
эту ошибку разработчики должны были вернуть c кодом ошибки клиента ([группа 4хх](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses)). 
Но случается и так, что ответ имеет статус код 200, а тело ответа содержит сообщение об ошибке, как в нашем примере. 
Такой ответ в любом случае необходимо обработать разработчику фронтенда (web, iOS, android).

 **Примеры состояний, когда такое происходит:**

- API key неверный
- API key просрочен
- количество запросов в день превышено (по документации не больше 100)

2023-07-08 13:17 UTC, protos17 requested changes

2023-07-10 08:29 UTC, protos17 commented on MovieQuiz/Services/StatisticService.swift
> +    }
Рекомендую заменить на:

    var totalAccuracy: Double {
        Double(correct) /  Double(total) * 100
    }

2023-07-13 13:08 UTC, Dmitrii-Diadiushkin commented on MovieQuiz/Services/QuestionFactory.swift
> +                self.delegate?.didFailToLoadData(with: "Не удалось загрузить постер" as! Error)
просто так из String Error не сделать - будет ошибка. Нужно создавать например enum типа Error по аналогии с NetworkClient. Также обрати внимание, что работа с UI должна выполняться на главном потоке

2023-07-16 10:45 UTC, merged